name: app

type: 'nodejs:12'

hooks:
  build: |
    if [ ! -f .platform.installed ]; then
        mkdir tmp
        ln -s tmp/.env .env
        touch .platform.installed
    fi
  deploy: |
    if [ ! -f .platform.installed ]; then
        mv tmp/.env run/.env
    fi

disk: 256

mounts:
  'run':
    source: local
    source_path: run

web:
  commands:
    start: "npm start"
    # start: "node -r dotenv/config main.js dotenv_config_path=/app/run/.env"
