name: app

type: 'nodejs:12'

hooks:
  build: |
    ln -s run/.env .env
    if [ -f run/.env ]; then
      export NODE_ENV=production
    fi
  deploy: |
    export WEBHOOK_PROXY_URL=$(node setup/getwebhook_url.js)

disk: 256

mounts:
  'run':
    source: local
    source_path: run

web:
  commands:
    start: "npm start"
