name: app

type: 'nodejs:12'

hooks:
  build: |
    if [ ! -f .platform.installed ]; then
        touch .platform.installed
        ln -s run/.env .env
    fi
    chmod +x getwebhook_url.sh
    . getwebhook_url.sh

disk: 256

mounts:
  'run':
    source: local
    source_path: run

web:
  commands:
    start: "npm start"
