name: app

type: 'nodejs:12'

hooks:
  build: |
    ln -s run/.env .env
    if [ -f run/.env ]; then
      export NODE_ENV=production
    fi
  deploy: |
    node setup/getwebhook_url.js
    export NODE_ENV=productiond

disk: 256

mounts:
  'run':
    source: local
    source_path: run

web:
  commands:
    start: "npm start"
