name: app

type: 'nodejs:12'

hooks:
  build: |
    if [ ! -f .platform.installed ]; then
        touch .platform.installed
        ln -s run/.env .env
        node getwebhook_url.js
    fi
  deploy: |
    node getwebhook_url.js

disk: 256

mounts:
  'run':
    source: local
    source_path: run

web:
  commands:
    start: "npm start"
