name: app

type: 'nodejs:12'

# Small change.
hooks:
  build: |
    if [ -z "${WEBHOOK_SECRET}" ]; then
        ln -s run/.env .env
    else
        mv run/.env .env
    fi

disk: 256

mounts:
  'run':
    source: local
    source_path: run

web:
  commands:
    start: "npm start"
