name: app

type: 'nodejs:12'

hooks:
  build: |
    node setup/getwebhook_url.js
    ln -s run/.env .env

disk: 256

mounts:
  'run':
    source: local
    source_path: run

web:
  commands:
    start: "npm start"
